env: "dev"

# storage_path:  "storage/storage3.db"

# http_server:

#   address: "localhost:8083"

#   host: "localhost"
#   post: 5431
#   user: "postgres"
#   password: root
#   dbname: first_db



postgres:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "root"
  dbname: "first_db"
  sslmode: "disable"  # optional, but useful for local dev

http_server:
  address: "localhost:8083"






